# Build Geth in a stock Go builder container
FROM golang:1.9-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers

ADD . /commerciumx
RUN cd /commerciumx && make all

# Pull all binaries into a second stage deploy alpine container
FROM alpine:latest

RUN apk add --no-cache ca-certificates
COPY --from=builder /commerciumx/build/bin/* /usr/local/bin/

EXPOSE 1911 1912 2019 2019/udp 2020/udp
